#Nome da aplicação e conexão com rabbitmq
spring:
  application:
    name: mscartoes
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
#Configurando porta
server:
  port: 0
  
#Localizando o eureka e setando nome com sufixo aleatorio - não pode esquecer do /eureka
eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:smu-sroekreuurac-es@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#Configurações da fila
mq:
  queues:
    emissao-cartoes: emissao-cartoes