spring:
  application:
    name: msavaliadorcredito
  rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    
server:
  port: 0
  
eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:smu-sroekreuurac-es@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#Configurando a fila
mq:
  queues:
    emissao-cartoes: emissao-cartoes
    
# Expondo todos os endpoints do actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

# Criando nosso arquivo de log
logging:
  file:
    name: ./logs/log-file.log
    
    